function Hd = HighpassFilter
%HIGHPASSFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 28-Oct-2015 15:42:45

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 3000;  % Sampling Frequency

Fstop = 90;          % Stopband Frequency
Fpass = 100;         % Passband Frequency
Astop = 65;          % Stopband Attenuation (dB)
Apass = 0.5;         % Passband Ripple (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
