library(irr)
Gears <- read.table("GEARS_RndAll.csv", header=FALSE, sep=",")
Gears1 <- read.table("GEARS1_RndAll.csv", header=FALSE, sep=",")
Gears2 <- read.table("GEARS2_RndAll.csv", header=FALSE, sep=",")
Gears3 <- read.table("GEARS3_RndAll.csv", header=FALSE, sep=",")
Gears4 <- read.table("GEARS4_RndAll.csv", header=FALSE, sep=",")
Gears5 <- read.table("GEARS5_RndAll.csv", header=FALSE, sep=",")
print(icc(Gears,model='twoway',type='agreement',unit='average'))
print(icc(Gears1,model='twoway',type='agreement',unit='average'))
print(icc(Gears2,model='twoway',type='agreement',unit='average'))
print(icc(Gears3,model='twoway',type='agreement',unit='average'))
print(icc(Gears4,model='twoway',type='agreement',unit='average'))
print(icc(Gears5,model='twoway',type='agreement',unit='average'))
